### ISSUE TITLE
Collectibles tab is empty

### ISSUE THREAD

**Issue by Something54363** [zatherz/BasementBuilder#1]
Title. Also screencap: ![WHY IS THE COLLECTIBLES TAB FUCKING EMPTY (jk i aint that mad about it (but it's still annoying))](http://i.imgur.com/pJHjtPC.png?1)

**Comment by Something54363** [comment]
cmon @zatherz please respond (btw i'm leo40reddit)

**Comment by zatherz** [comment]
Fixed in latest commit and 1.0.2.
