### ISSUE TITLE
BasementBuilder crashes on when viewing Womb room #424

### ISSUE THREAD

**Issue by Zamiell** [zatherz/BasementBuilder#2]
Not much more to say; this bug should be easily reproducible.

**Comment by zatherz** [comment]
Interesting. It's also an upstream issue. I'm searching for a fix.

**Comment by Zamiell** [comment]
Well it doesn't crash on the Basement Renovator but it just won't display the 2nd half of the room.

**Comment by zatherz** [comment]
Oh, I see. You're right. Super weird.

**Comment by zatherz** [comment]
Wait, that's not right. In both Basement Renovator and Builder it hangs the program for me, but interrupting the program with Ctrl+C (sending the SIGINT signal) renders half of the room properly. It must be stuck on something.

**Comment by zatherz** [comment]
Found the entity it's stuck on. Analyzing right now...

**Comment by zatherz** [comment]
Two entities in one place seems to be the issue.

**Comment by zatherz** [comment]
The room is improperly saved by Nicalis. There are two spawns with two entities at the same spot, while there should be 1 spawn with two entities. One spawn per one place. NICALIS!! D: Now to find out how to workaround that...

**Comment by zatherz** [comment]
Now, this is getting crazier...

**Comment by zatherz** [comment]
Nevermind, it's not related to the save at all. It's related to the entity ID being for some reason not in Basement Builder. I don't know what entity this is.

**Comment by zatherz** [comment]
Fixed! Expect 1.0.3 soon.
